### PR TITLE
Update LayerCollectionRenderer to use MapViewport / Fix issues with Map.MapTransform

### PR DESCRIPTION
**Pull request by terribletim**
Update to resolve error with Map.MapTransform: **Matrix.get_IsIdentity() Object is currently in use elsewhere**. Since applying these changes, I am not seeing any errors in the log files.<br/><br/>

**Overview of changes**<br/>

`MapViewport`<br/>

- Change `public static implicit operator MapViewport(Map map)` - lock no longer required on `Map.MapTransform` due to changes in `Map `(see below)<br/>
- internal locks no longer required, as all operations using `MapTransform` or `MapTransformInverted` use clones <br/>
- cache result from `GetMapScale` for specified **dpi**<br/><br/>

`Map` <br/>
- Modify locking on `MapTransform` to use internal object, and Getter returns **clone**.<br/>
- Change `MapTransformInverted` accessor from `internal` to `private`. This requires minor changes to `MapViewport` instantiation as described above.<br/>
- Update `ImageToWorld` and `WorldToImage` as locks no longer required on `MapTransform`<br/>
- Modify `Map.Render*` methods to use `MapViewport `instead of `Map`. Intentional double locking on _`lockMapTransform `when configuring graphics transform and instantiating `MapViewport`<br/><br/>

`LayerCollectionRenderer`<br/>
**This is the key to removing lock contentions** described in #76 and #94 which I was also experiencing. <br/>
- new method `public void Render(Graphics g, MapViewport mapViewPort, bool allowParallel)` and `obsolete `old method with map arg<br/>
- updates throughout class to use `MapViewport` instead of `Map`<br/><br/>

`LayerListImageGenerator`<br/>
- simplify instantiation of `MapViewport` due to changes in `Map.MapTransform`<br/><br/>

**Side issues**<br/>
- If these changes are acceptable, there will be an associated set of minor changes to all classes that currently clone Map.MapTransform, as the Getter now returns a clone.<br/>
- `MapDecoration` should probably also be updated at some point to use `MapViewport `rather than `Map`<br/>

### CODE REVIEW

**Comment by terribletim** [comment]
Working on Issue #106, it may be helpful to know if `MapTransform` is identity. Wondering if it is a good idea to expose this as read-only property on the Map class? <br/>
It would also make `WorldToImage` and `ImageToWorld` functions more efficient in the majority of cases.

**Comment by terribletim** [comment]
FYI - will be adding commit to this branch with read-only property `MapTransformRotation` managed by `MapTransform` setter. Hopefully by the end of the weed.

**Comment by terribletim** [comment]
Added prop `MapTransformRotation` and updated `WorldToIMage` and `ImageToWorld` functions to minimize use of locks.

**Comment by terribletim** [comment]
Hi - just wondering if anyone has had time to take a look at this?

**Review by FObermaier — APPROVED** [review]
Thanks, I'm fine with these changes.
@becio, you too?

**Review by becio — APPROVED** [review]

**Pull request merged**
