### PR TITLE
Refactor OleDbPoint provider to XYColumnPoint provider

### PR DESCRIPTION
**Pull request by joriswit**
I changed the OleDbPoint provider to use the Common ADO.NET provider framework, to allow the provider to also work with non-OLEDB data sources. I added tests to use it with SQLite. I also changed the original tests to detect the OLEDB MS Access provider, and ignore the test if it is unavailable.

(this might be useful for the .NET Standard 2 as well, since the OLEDB provider is not part of .NET standard 2. However, I have not tested this)

I did the same with the OleDbTwoPointLine provider, but I have not added it to the project file, because it has a failing test.

### CODE REVIEW

**Comment by FObermaier** [comment]
This is appreciated. Could you rebase it on the refactor/netStandard branch?
Thanks

**Comment by FObermaier** [comment]
@joriswit I rebased this PR on the latest changes on SharpMap's Branch/1.0.
I reverted the deletion of `OleDbPoint` and `OleDbTwoPointLine` providers. They are being ignored for `NETSTANDARD`.

Could you please review. I must admit that I'm not comfortable with the naming of the providers but don't have a better idea atm.

**Comment by joriswit** [comment]
@FObermaier Thanks for rebasing! I couldn't get Git to do it!

I tested the provider in it's rebased form, and it works perfectly.

About the deletion of `OleDbPoint`, I did not delete it, I just changed it to be a subclass of the new `XYColumnPoint` provider. I would prefer to have it as a subclass, otherwise all the code is duplicated. I believe the new provider is 100% compatible with the old `OleDbPoint` provider, all the `OleDbPoint` tests work unchanged. But if you want to keep the `OleDbPoint` provider unchanged I am fine with that too.

The `OleDbTwoPointLine` class is a different issue. It was not included in the old `SharpMap.csproj` file, so backwards compatibility is not an issue. In fact, I am not sure we should even include the `XYColumnTwoPointLine` provider. This is because it has a (not easy to fix) bug in the `ExecuteIntersectionQuery` method. I demonstrated this in the `TestExecuteIntersectionQueryAgainstGeometryIntersectionButNoPointsWithin` test. If you do decide to keep the provider, the `XYColumnTwoPointLineProviderTest.cs` file containing the failing test should also be included in the `UnitTests.csproj` file.

About the name, it was the best I could think of. I first thought naming it `AdoNetPoint`, named after the database framework (like `OleDbPoint`). But since using ADO.NET is not the distinctive feature of this provider, I picked `XYColumnPoint`.

**Comment by FObermaier** [comment]
I fixed the `GetSpatialConstraint` function in `XYColumnTwoPointLine` provider thus making the unit test pass.

I'd prefer `DbPoint` and `DbTwoPointLine` as provider names, or instead of `Db` `DataCommon`.

**Comment by FObermaier** [comment]
Could you post the inheritance of `OleDbPoint` using `XyColumnPoint` again, please. `git push -force` made your version unavailable

**Comment by joriswit** [comment]
Nicely done with the `XYColumnTwoPointLine` provider! I have re-committed the `OleDbPoint` provider. I did not change the `OleDbTwoPointLine` provider, as I think it should be deleted.

Would you like me to rename the `XYColumnPoint` provider to `DbPoint` or `DataCommonPoint`? I am fine with all these names :-)

**Review by FObermaier — APPROVED** [review]
Thanks @joriswit for your collaboration on this

**Pull request merged**
