### PR TITLE
Refactor towards .Net Standard

### PR DESCRIPTION
**Pull request by FObermaier**
This PR transforms both `SharpMap` and `SharpMap.Layers.BruTile` projects into multi-target dotnet sdk projects. The targets are `net40-client`, `net452` and `netStandard20`.

Along with this effort
* unit tests have been reviewed, fixed or disabled for Travis CI,
* components have been updated

### CODE REVIEW

**Review by joriswit — COMMENTED** [review]
I had trouble compiling, but it turned out I simply needed to update my VS 2017 to the latest patch :-)

I still got a lot of errors because SharedAssemblyVersion.cs does not exist. I seems to be created in a post-build step, but I get the error '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Binmsbuild"' is not recognized as an internal or external command, operable program or batch file. The $(MSBuildBinPath) variable seems to not have the backslash included on my system.

After I copied SharedAssemblyVersion.cs myself, and fixing SurrogatesTest line#137, I was able to build SharpMap.

The SharpMap.Demo.Wms project probably does not build because the project still refers to SQLite 1.0.94.0.

I do not have a .NET standard 2 project to test if everything works, so I just looked at the code.

I noticed you added a few classes in SharpMap.Drawing. Some are internal, but some are public. Should they all be internal? Also, the #if NETSTANDARD2_0 is not in all files.

(BTW: I have not yet succeeded to rebase PR 113; git is hard :-) )

**Comment by joriswit** [comment]
Thanks for the fix! Still a few problems; The projects SharpMap.Converters.Spatialite and SharpMap.CoordinateSystems.DotSpatial so not have a reference to SharpMap.dll, so they may be built before the SharpMap post-build step is executed. Perhaps a solution dependency is required here to prevent the SharedAssemblyVersion.cs error in the first build (see joriswit/SharpMap@db60523905157c47ec5140f4f7a74717997c2267 ).

**Comment by joriswit** [comment]
In my previous post I thought the SharedAssemblyInfo problem was solved, but it seems I did not test it correctly. After getting a fresh clone, I have this problem again. However, there is no error in the build log anymore. The cause seems to be that the PostBuildEvent in the project file has a condition that does not return true on my (Windows) system.

Other problems:
The SharpMap.Demo.Wms build fails because it references SQLite 1.0.94.0.
The SharpMap.Data.Providers.FileGdb post-build step fails when the folder contains a space.

**Comment by terribletim** [comment]
I have attached the NuGet log in case it is of any use. It shows that I installed Microsoft.CSharp 4.5.0 (replacing Microsoft.CSharp 4.0.1)

[NuGet Microsoft.CSharp.txt](https://github.com/SharpMap/SharpMap/files/2522956/NuGet.Microsoft.CSharp.txt)

**Comment by terribletim** [comment]
I now see the conditional compile statements related to **KnownColor** and elsewhere. However, there is some variation throughout the project:
`#if NETSTANDARD`
`#if NETSTANDARD2_0`

If I change all to NETSTANDARD2_0 then project compiles. Wondering if NETSTANDARD was meant to have been defined as a compile constant somewhere? I can't see anything in the csproj file, but I did see a warning message flash up about csproj format (sorry - didn't get any more info) and wondering if this might relate to other dependency issues mentioned above. 

FYI - **KnownColor** has apparently been added to NuGet System.Drawing.Common 4.5.1 but this is not compatible with other packages used by SharpMap.

**Comment by FObermaier** [comment]
Which product do you use to compile the solution?
I did a fresh clone and do neither need to install `Microsoft.CSharp` package into SharpMap project nor does the solution complain about `#if NETSTANDARD`.

**Comment by terribletim** [comment]
I'm using Visual Studio 2017 v15.7.5

Diff on **SharpMap.csproj** which shows:

**Adds:**
```
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.CSharp">
      <Version>4.5.0</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net452'">
    <PackageReference Include="Microsoft.CSharp">
      <Version>4.5.0</Version>
    </PackageReference>
  </ItemGroup>
```
**Deletes:**
` &#xD;&#xA;` removed from ExecCondition at end of file

**Comment by terribletim** [comment]
Here's some more info.

1. Sync local with upstream
`git fetch upstream`
`git checkout Branches/1.0`
`git merge upstream/Branches/1.0` (accepting Source on several differences for csproj files)

2. Open in VS and try to build solution. There are 30+ errors.... all related to NETSTANDARD vs NETSTANDARD2_0. Project compiles successfully after changing the following files to `NETSTANDARD2_0` 
- SharpMap.Data.Providers.OleDbPoint
- SharpMap.Rendering.Symbolizer.Utility
- SharpMap.Rendering.Symbolizer.Utility
- SharpMap.Styles.VectorStyle

Notes:
- this time I didn't install NuGet package **Microsoft.CSharp**. All Dependencies were resolved correctly, so guess the initial install caused something to be registered on my computer?
- this time the compilation / restoring NuGet Packages did not result in any changes to csproj files 
- I can't see NETSTANDARD listed as a preprocessor symbol for [Microsoft Target Frameworks](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-framework-versions) (scroll down to just before Deprecated Frameworks). However, I did see something about defining constants such as NETSTANDARD but couldn't find anything like this in SharpMap 
```
<PropertyGroup Condition="$([System.Text.RegularExpressions.Regex]::IsMatch('$(TargetFramework)', '^netstandard\d'))">
  <DefineConstants>NETSTANDARD</DefineConstants>
</PropertyGroup>
```

**Comment by FObermaier** [comment]
Could you do a fresh clone on the original repository please and see if the problem persists?

**Comment by terribletim** [comment]
After downloading zip file for Branches/1.0 and restoring NuGet packages, have the following errors:

1. Various **SharedAssemblyVersion.cs** cannot be found
2. _~\SharpMap-Branches-1.0\SharpMap\obj\**project.assets.json**' not found. Run a NuGet package restore to generate this file_  of which 
- 3 errors relate to:
```
    <CheckForTargetInAssetsFile
      AssetsFilePath="$(ProjectAssetsFile)"
      TargetFrameworkMoniker="$(NuGetTargetMoniker)"
      RuntimeIdentifier="$(RuntimeIdentifier)" />
```
- and 3 more errors relate to:
```
    <ReportAssetsLogMessages
      ProjectAssetsFile="$(ProjectAssetsFile)"
      ContinueOnError="ErrorAndContinue">
      <Output TaskParameter="DiagnosticMessages" ItemName="DiagnosticMessages" />
    </ReportAssetsLogMessages>
```
3. Dependencies for .NetFramework 4.0, .NetFramework 4.5.2, and .NetStandard 2.0 have yellow warning triangles

I manually copied SharedAssemblyVersion.cs into SLN folder which got rid of some of the errors, but still unable to compile SharpMap. Tried the **Microsoft.CSharp** package again - ok this is forcing the creation of project.assets.json, leaving me with the `NETSTANDARD` problem. 

Microsoft.CSharp 4.5.0 uninstalls the following (may NETSTANDARD is exposed in one of them?):

- System.Dynamic.Runtime.4.0.11
- System.Linq.4.1.0
- Sytem.Linq.Expressions.4.1.0
- System.ObjectModel.4.0.12
- System.Reflection.Emit.4.0.1
- System.Reflection.Emit.ILGeneration.4.0.1
- System.Reflection.Emit.LightWeight.4.0.1
- System.Reflection.Extensions.4.0.1
- System.Resources.ResourceManager.4.0.1
- System.RUntime.Handles.4.0.1
- System.Runtime.InteropServices.4.1.0

I'll repeat the above, this time without the default action of updating Microsoft.CSharp from 4.0.1 to 4.5.0 and let you know the outcome.

**Comment by FObermaier** [comment]
On the first build I do get the `SharedAssemblyVersion.cs` errors as well.
Not changing anything, the second build has no errors.

**Comment by terribletim** [comment]
OK - the Microsoft.CSharp package was a red herring.... there was another error when I tried to restore packages via SLN context menu **Restore NuGet Packages**. Turned out that Tools / Options / NuGet Package Manager / General **Allow NuGet to download missing packages** was unchecked. Enabling this option resolves Item 2 above. Sorry for the fiasco.</br>
However, still getting `NETSTANDARD `error.

**Comment by terribletim** [comment]
Confirmed - the `SharedAssemblyVersion.cs `error is also a red herring, as this is auto-generated when building SharpMap project.

**Pull request merged**
