### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Jymbul**
Please, I need the latest Web Demo to fathom out some ideas!

### CODE REVIEW

**Comment by FObermaier** [comment]
Why do you need to do it on master branch?

**Comment by Jymbul** [comment]
Hi Felix

I am new to github, Sorry.  There used to be a web demo for sharpmap on
codeplex.  I am not sure how to download the demo files from github.

I don't want to change anything,  Sorry for me confusion.

Best regards
James

**Comment by FObermaier** [comment]
Accidental

**Comment by FObermaier** [comment]
On the top-right part of the [start page](https://github.com/SharpMap/SharpMap) there is a green **Clone or Download** button to get you started.

**Comment by Jymbul** [comment]
Hi Felix

Thanks for that!  Just realised myself.

Sorry for being a bit dense - it's all a bit different from CodePlex!

Best regards
James D Nelson

**Pull request closed without merging**
